CREATE SCHEMA IF NOT EXISTS helenos AUTHORIZATION helenos;
CREATE TABLE IF NOT EXISTS USERS(USERNAME VARCHAR(32) PRIMARY KEY,PASSWORD VARCHAR(255), AUTHORITIES VARCHAR(255), ENABLED BOOLEAN);
CREATE TABLE IF NOT EXISTS CLUSTERCONFIG(ALIAS VARCHAR(128) PRIMARY KEY,HOSTS VARCHAR(255), CLUSTERNAME VARCHAR(255), ACTIVE BOOLEAN, USERNAME VARCHAR(64), PASSWORD VARCHAR(64));
